### ISSUE TITLE
-i option

### ISSUE THREAD

**Issue by wshaf97** [HuggableSquare/vsco-dl#11]
What format does the text file need to be in order to function? And could you provide an example command to use this? Where does the text file need to be located?

**Comment by HuggableSquare** [comment]
The text file should be a new line separated file of either usernames or siteIds (if using the -s option). The file can be located anywhere, you specify where it looks for the file when using the command.
e.g. the file should look something like this:
```
username1
username2
username3
```
and you would use it by calling the script like this: `ruby vsco-dl.rb -i /path/to/file.txt`

OR if you wanted to use siteIds the file should look like this:
```
123456
123457
123458
```
and you would use it by calling the script like this: `ruby vsco-dl.rb -i /path/to/file.txt -s`
