### ISSUE TITLE
open-uri.rb:378:in `open_http': 403 Forbidden (OpenURI::HTTPError)

### ISSUE THREAD

**Issue by wshaf97** [HuggableSquare/vsco-dl#14]
It's crazy that I continue to use this script, but recently it stopped working. When attempting to open a username it returns 

Loading initial dataC:/Ruby26/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 403 Forbidden (OpenURI::HTTPError)
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:736:in `open'
        from C:/Ruby26/lib/ruby/2.6.0/open-uri.rb:35:in `open'
        from C:/Users/xxxx/vsco.rb:52:in `download'
        from C:/Users/xxxx/vsco.rb:137:in `<main>'
       
Unsure of what is causing this issue. I have used 2.6 Ruby the whole time.

**Comment by HuggableSquare** [comment]
Super late reply, but should be fixed now!
