### ISSUE TITLE
Add option to download multiple users from a text file

### ISSUE THREAD

**Issue by bamtan** [HuggableSquare/vsco-dl#7]
Thanks for making this tool! I was wondering if you could add the ability to scrape multiple users using a text file?

For example 
```
-a, --all                Download a list of users from a text file

vsco-dl.rb -a list.txt
```

**Comment by HuggableSquare** [comment]
This one should work now too! Each name should be separated by a new line in the file, and it should work fine with every other option (including the site id option).

```
-i, --input=file.txt             Download all users from an input file
```

**Comment by bamtan** [comment]
Thanks so much! It works great 😄
