### ISSUE TITLE
Scrape users by site_id

### ISSUE THREAD

**Issue by bamtan** [HuggableSquare/vsco-dl#8]
Would it be possible to add the option to scrape a user by their site_id? In the case of a username change, the _siteId_ does not change, so that would be good for keeping track of a user.

Method for getting siteId
1. Inspect source of target user: https://vsco.co/benchtheprod/images/1
2. Ctrl+F "siteID": 95787455

API for getting user information: `https://api.vsco.co/2.0/sites/<siteId>` (requires Bearer token)

---

```
-sid, --siteid                Download using siteId instead of username

vsco-dl.rb -sid 95787455
```

Let me know 😄

**Comment by HuggableSquare** [comment]
Added! Thank you for providing the api endpoint (that made this significantly easier), but apologies for taking so long to work on this.
```
-s, --site-id                    Download user via site id instead of username
```

**Comment by bamtan** [comment]
Thank you so much!
