### ISSUE TITLE
Fatal error during HTTP > HTTPS redirect before ruby >=2.4

### ISSUE THREAD

**Issue by Jefferderp** [HuggableSquare/vsco-dl#9]
Ruby versions prior to 2.4 would fail with `redirect forbidden` when attempting to redirect HTTP to HTTPS.

VSCO appears to be hosted on Amazon AWS, which does perform one or more such redirects.

Described in more detail:
https://blog.bigbinary.com/2017/03/02/open-uri-in-ruby-2-4-allows-http-to-https-redirection.html

Also, I note that (at least on Ubuntu 16.10) the script must be executed with `ruby vsco-dl.rb`, and not just `vsco-dl.rb`. A small point.

Just a heads up, in case you'd like to update the README.

Great piece of software, thanks!

**Comment by HuggableSquare** [comment]
Yeah I noticed this awhile ago, I'm gonna leave a note in the README quickly since it's even tripped me up before. Appreciate you taking the time to make this issue!
